### PR TITLE
Fix #144. Add support for Tempfile

### LINKED ISSUE #144: Display from Active Storage
I have disabled Active Storage from displaying the image as a blob by adding an initializer with the following:

```
Rails.application.config.active_storage.content_types_to_serve_as_binary.delete('image/svg+xml')
```

However, I am still unable to do something like the following `<%= inline_svg_tag product.product_icon, class: 'h-6 w-6', aria: { hidden: true } %>` without an error being thrown. Not entirely sure what I am doing wrong.

### PR DESCRIPTION
**Pull request by javierav**
If we want to use this gem with an SVG stored in Active Storage, we have to temporarily download the file and then use it with gem helper

```ruby
module SvgHelper
  def remote_svg(blob, **)
    blob.open do |file|
      inline_svg_tag file, **
    end
  end
end

# in views
<%= remote_svg(user.icon) %>
```

The problem is that Active Storage uses a temporary file with the `Tempfile` class that uses `DelegateClass` over `File`, so technically it behaves like a `File` but does not inherit from it, so it could not be used with this gem.

This PR fixes that issue by providing support for `Tempfile`.

### CODE REVIEW

File: lib/inline_svg/io_resource.rb [hunk 1]
```diff
@@ -3,14 +3,7 @@
...
-      object.is_a?(IO) || object.is_a?(StringIO)
-    end
-
-    def self.default_for(object)
-      case object
-      when StringIO then ''
-      when IO then 1
-      end
+      object.is_a?(IO) || object.is_a?(StringIO) || object.is_a?(Tempfile)
     end
```
Comment (tagliala) [inline lib/inline_svg/io_resource.rb:7]: hello, I understand that `default_for` appears not to be used by this library and it is not even tested, but is there a reason to remove it entirely?

Comment (javierav) [reply lib/inline_svg/io_resource.rb:7]: Great, I think it's a great option. As soon as the other PR is up, I'll update this one!

**Comment by tagliala** [comment]
@javierav can you please rebase and add an entry in the changelog?

**Comment by javierav** [comment]
Done @tagliala! I've simplified the commit and PR name to refer only `Tempfile`. I've also added a simple entry to the readme on how to use it with ActiveStorage. Feel free to add a better description if you see fit. We look forward to hearing from @jamesmartin!

**Review by tagliala — APPROVED** [review]

**Review by jamesmartin — APPROVED** [review]
Thanks for the PR, @javierav. Agree with @tagliala that this change is worth merging as-is. 👍
